version: "3.8"


services:
  airflow:
    container_name: airflow
    image: airflow
    build:
      context: ./docker/airflow
      dockerfile: Dockerfile
    env_file:
      - ./env/mlflow.env
      - ./env/airflow.env
    ports:
      - 8080:8080
    volumes:
      - ./src/app:/opt/airflow/app
      - ./src/dags:/opt/airflow/dags
      - ./src/files:/opt/airflow/files
      - ./src/alembic:/opt/airflow/alembic
      - ./src/alembic.ini:/opt/airflow/alembic.ini
      - ./config/airflow.cfg:/opt/airflow/airflow.cfg
      - ./keys:/opt/airflow/keys
    depends_on:
      - db
      - mlflow
      - redis

  mlflow:
    container_name: mlflow
    image: mlflow
    build:
      context: ./docker/mlflow
      dockerfile: Dockerfile
    env_file: ./env/mlflow.env
    ports:
      - 8000:8000
    volumes:
      - ./src:/home/mlflow/mlflow
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

  streamlit:
    container_name: streamlit
    image: streamlit
    build:
      context: ./docker/streamlit
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    command: streamlit run app.py --server.port 5000
